name: Ruby

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"

    name: Ruby ${{ matrix.ruby }} test
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Install dependencies
        run: bundle install

      - name: Run Tests
        run: |
          bundle exec rake test
